# Generated by Django 4.2.5 on 2023-10-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonviewer',
            name='last_viewed_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
